package com.surya.trex.notifications

import android.app.Notification
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import android.util.Log

import com.surya.trex.data.local.TokenManager
import com.surya.trex.data.model.PendingTransactionCreateRequest
import com.surya.trex.data.model.Transaction
import com.surya.trex.data.model.TransactionSource
import com.surya.trex.data.repository.CategoryRepository
import com.surya.trex.data.repository.PendingTransactionRepository
import com.surya.trex.data.repository.SettingsRepository
import com.surya.trex.data.repository.TransactionRepository
import com.surya.trex.sms.ParsedSmsTransaction
import com.surya.trex.sms.SmsTransactionParser

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch

import java.security.MessageDigest
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone

class AppNotificationListenerService : NotificationListenerService() {

    companion object {

        private const val TAG = "TREX_NOTIFICATION"

        private const val MODE_AUTO = "AUTO"
        private const val MODE_APPROVAL = "APPROVAL"

        private const val SOURCE_APP_NOTIFICATION =
            "APP_NOTIFICATION"

        private const val SOURCE_BOTH =
            "BOTH"
    }

    private val serviceScope =
        CoroutineScope(
            SupervisorJob() + Dispatchers.IO
        )

    // =========================================================
    // Notification received
    // =========================================================

    override fun onNotificationPosted(
        sbn: StatusBarNotification
    ) {

        try {

            /*
             * Ignore notifications generated by TREX itself.
             */
            if (sbn.packageName == packageName) {
                return
            }

            serviceScope.launch {

                try {

                    processNotification(sbn)

                } catch (e: Exception) {

                    Log.e(
                        TAG,
                        "Notification processing failed",
                        e
                    )
                }
            }

        } catch (e: Exception) {

            Log.e(
                TAG,
                "Failed to schedule notification processing",
                e
            )
        }
    }

    // =========================================================
    // Service destroyed
    // =========================================================

    override fun onDestroy() {

        serviceScope.cancel()

        super.onDestroy()
    }

    // =========================================================
    // Process notification
    // =========================================================

    private suspend fun processNotification(
        sbn: StatusBarNotification
    ) {

        /*
         * Get logged-in user's JWT.
         */
        val token =
            TokenManager(applicationContext)
                .getToken()
                ?: run {

                    Log.d(
                        TAG,
                        "No authentication token. Ignoring notification."
                    )

                    return
                }

        val settingsRepository =
            SettingsRepository()

        // =====================================================
        // Load settings
        // =====================================================

        val settings =
            try {

                settingsRepository.getSettings(
                    token
                )

            } catch (e: Exception) {

                Log.e(
                    TAG,
                    "Could not load TREX settings",
                    e
                )

                return
            }

        /*
         * This is the master transaction-detection switch.
         *
         * OFF:
         *      Do not process SMS/app notifications.
         *
         * ON:
         *      Continue processing.
         */
        if (!settings.sms_detection_enabled) {

            Log.d(
                TAG,
                "Transaction detection is disabled."
            )

            return
        }

        // =====================================================
        // Load configured sources
        // =====================================================

        val sources =
            try {

                settingsRepository.getSources(
                    token
                )

            } catch (e: Exception) {

                Log.e(
                    TAG,
                    "Could not load transaction sources",
                    e
                )

                return
            }

        // =====================================================
        // Find matching installed-app source
        // =====================================================

        val source =
            sources.firstOrNull { sourceItem ->

                if (!sourceItem.enabled) {
                    return@firstOrNull false
                }

                val sourceType =
                    sourceItem.source_type
                        .trim()

                val isNotificationSource =
                    sourceType.equals(
                        SOURCE_APP_NOTIFICATION,
                        ignoreCase = true
                    ) ||
                            sourceType.equals(
                                SOURCE_BOTH,
                                ignoreCase = true
                            )

                val configuredPackage =
                    sourceItem.package_name
                        ?.trim()
                        .orEmpty()

                isNotificationSource &&
                        configuredPackage.isNotBlank() &&
                        configuredPackage.equals(
                            sbn.packageName,
                            ignoreCase = true
                        )
            }

        /*
         * If this application was not selected by the user,
         * ignore its notification.
         */
        if (source == null) {

            Log.d(
                TAG,
                "Ignoring notification from unconfigured app: " +
                        sbn.packageName
            )

            return
        }

        Log.d(
            TAG,
            "Matched source: ${source.app_name}"
        )

        // =====================================================
        // Read notification
        // =====================================================

        val extras =
            sbn.notification.extras

        val title =
            extras
                .getCharSequence(
                    Notification.EXTRA_TITLE
                )
                ?.toString()
                ?.trim()
                .orEmpty()

        val bigText =
            extras
                .getCharSequence(
                    Notification.EXTRA_BIG_TEXT
                )
                ?.toString()
                ?.trim()
                .orEmpty()

        val normalText =
            extras
                .getCharSequence(
                    Notification.EXTRA_TEXT
                )
                ?.toString()
                ?.trim()
                .orEmpty()

        val text =
            when {

                bigText.isNotBlank() ->
                    bigText

                normalText.isNotBlank() ->
                    normalText

                else ->
                    ""
            }

        if (
            title.isBlank() &&
            text.isBlank()
        ) {

            Log.d(
                TAG,
                "Notification contains no readable text."
            )

            return
        }

        // =====================================================
        // Build complete message
        // =====================================================

        val message =
            listOf(
                title,
                text
            )
                .filter {
                    it.isNotBlank()
                }
                .joinToString(" - ")

        if (message.isBlank()) {
            return
        }

        Log.d(
            TAG,
            "Notification received from " +
                    "${source.app_name}: $message"
        )

        // =====================================================
        // Notification timestamp
        // =====================================================

        val timestamp =
            sbn.postTime

        // =====================================================
        // Parse transaction
        // =====================================================

        val parsed =
            SmsTransactionParser.parse(
                message = message,
                timestampMillis = timestamp
            )

        if (parsed == null) {

            Log.d(
                TAG,
                "Notification is not a transaction: $message"
            )

            return
        }

        Log.d(
            TAG,
            "Transaction detected: " +
                    "amount=${parsed.amount}, " +
                    "type=${parsed.transactionType}, " +
                    "description=${parsed.description}"
        )

        // =====================================================
        // Fingerprint
        // =====================================================

        val fingerprint =
            createFingerprint(
                packageName = sbn.packageName,
                message = message,
                timestamp = timestamp
            )

        // =====================================================
        // Detection mode
        // =====================================================

        when (
            settings.detection_mode
                .trim()
                .uppercase()
        ) {

            // =================================================
            // APPROVAL
            // =================================================

            MODE_APPROVAL -> {

                handleApprovalMode(
                    token = token,
                    source = source,
                    sbn = sbn,
                    message = message,
                    parsed = parsed,
                    timestamp = timestamp,
                    fingerprint = fingerprint,
                    notificationsEnabled =
                        settings.notifications_enabled
                )
            }

            // =================================================
            // AUTO
            // =================================================

            MODE_AUTO -> {

                handleAutoMode(
                    token = token,
                    parsed = parsed,
                    notificationsEnabled =
                        settings.notifications_enabled
                )
            }

            // =================================================
            // MANUAL
            // =================================================

            else -> {

                Log.d(
                    TAG,
                    "MANUAL mode enabled. " +
                            "Notification will not create a transaction."
                )
            }
        }
    }

    // =========================================================
    // APPROVAL MODE
    // =========================================================

    private suspend fun handleApprovalMode(
        token: String,
        source: TransactionSource,
        sbn: StatusBarNotification,
        message: String,
        parsed: ParsedSmsTransaction,
        timestamp: Long,
        fingerprint: String,
        notificationsEnabled: Boolean
    ) {

        /*
         * Convert timestamp to ISO-8601 format.
         *
         * We deliberately use SimpleDateFormat instead of
         * java.time.Instant because TREX supports minSdk 24.
         */
        val transactionDate =
            formatTimestamp(timestamp)

        val request =
            PendingTransactionCreateRequest(

                source_id =
                    source.id,

                app_name =
                    source.app_name,

                package_name =
                    source.package_name,

                source_type =
                    SOURCE_APP_NOTIFICATION,

                sender_id =
                    sbn.packageName,

                message_body =
                    message,

                amount =
                    parsed.amount.toPlainString(),

                transaction_type =
                    parsed.transactionType,

                description =
                    parsed.description,

                category_id =
                    null,

                transaction_date =
                    transactionDate,

                confidence =
                    "1.0",

                fingerprint =
                    fingerprint
            )

        val result =
            PendingTransactionRepository()
                .createPendingTransaction(
                    token = token,
                    request = request
                )

        result
            .onSuccess {

                Log.d(
                    TAG,
                    "Pending transaction created successfully."
                )

                /*
                 * Notification display is independent
                 * from transaction detection.
                 */
                if (notificationsEnabled) {

                    TransactionNotificationHelper.show(
                        applicationContext,
                        "Transaction detected",
                        "₹${parsed.amount.toPlainString()} detected from ${source.app_name}. Open TREX to review."
                    )
                }
            }
            .onFailure { error ->

                Log.e(
                    TAG,
                    "Failed to create pending transaction",
                    error
                )
            }
    }

    // =========================================================
    // AUTO MODE
    // =========================================================

    private suspend fun handleAutoMode(
        token: String,
        parsed: ParsedSmsTransaction,
        notificationsEnabled: Boolean
    ) {

        createAutomatically(
            token = token,
            parsed = parsed,
            settingsNotificationsEnabled =
                notificationsEnabled
        )
    }

    // =========================================================
    // Automatically create transaction
    // =========================================================

    private suspend fun createAutomatically(
        token: String,
        parsed: ParsedSmsTransaction,
        settingsNotificationsEnabled: Boolean
    ) {

        // =====================================================
        // Load categories
        // =====================================================

        val categories =
            CategoryRepository(
                TokenManager(applicationContext)
            )
                .getCategories()
                .getOrNull()
                ?: run {

                    Log.e(
                        TAG,
                        "Could not load categories."
                    )

                    return
                }

        // =====================================================
        // Filter categories by transaction type
        // =====================================================

        val candidates =
            categories.filter {

                it.category_type.equals(
                    parsed.transactionType,
                    ignoreCase = true
                )
            }

        if (candidates.isEmpty()) {

            Log.e(
                TAG,
                "No category found for transaction type: " +
                        parsed.transactionType
            )

            return
        }

        // =====================================================
        // Find matching category
        // =====================================================

        val category =
            candidates.firstOrNull {

                parsed.description.contains(
                    it.category_name,
                    ignoreCase = true
                )
            }
                ?: candidates.firstOrNull {

                    it.category_name.equals(
                        "Other",
                        ignoreCase = true
                    ) ||
                            it.category_name.equals(
                                "Uncategorized",
                                ignoreCase = true
                            )
                }
                ?: candidates.firstOrNull()

        if (category == null) {

            Log.e(
                TAG,
                "Could not determine category."
            )

            return
        }

        // =====================================================
        // Convert timestamp
        // =====================================================

        val transactionDate =
            formatDate(
                parsed.dateTimeMillis
            )

        val transactionTime =
            formatTime(
                parsed.dateTimeMillis
            )

        // =====================================================
        // Create Transaction
        // =====================================================

        val transaction =
            Transaction(

                category_id =
                    category.id,

                amount =
                    parsed.amount.toDouble(),

                description =
                    parsed.description,

                transaction_type =
                    parsed.transactionType,

                transaction_date =
                    transactionDate,

                transaction_time =
                    transactionTime
            )

        // =====================================================
        // Save transaction
        // =====================================================

        val result =
            TransactionRepository(
                TokenManager(applicationContext)
            )
                .createTransaction(
                    transaction
                )

        result
            .onSuccess {

                Log.d(
                    TAG,
                    "Automatic transaction created successfully."
                )

                /*
                 * Notification can be disabled without
                 * disabling automatic transaction creation.
                 */
                if (settingsNotificationsEnabled) {

                    TransactionNotificationHelper.show(
                        applicationContext,
                        "Transaction added",
                        "₹${parsed.amount.toPlainString()} was automatically added to TREX."
                    )
                }
            }
            .onFailure { error ->

                Log.e(
                    TAG,
                    "Automatic transaction creation failed",
                    error
                )
            }
    }

    // =========================================================
    // Format complete timestamp
    // =========================================================

    private fun formatTimestamp(
        timestamp: Long
    ): String {

        val formatter =
            SimpleDateFormat(
                "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
                Locale.US
            )

        formatter.timeZone =
            TimeZone.getTimeZone("UTC")

        return formatter.format(
            Date(timestamp)
        )
    }

    // =========================================================
    // Format date
    // =========================================================

    private fun formatDate(
        timestamp: Long
    ): String {

        val formatter =
            SimpleDateFormat(
                "yyyy-MM-dd",
                Locale.US
            )

        formatter.timeZone =
            TimeZone.getTimeZone("UTC")

        return formatter.format(
            Date(timestamp)
        )
    }

    // =========================================================
    // Format time
    // =========================================================

    private fun formatTime(
        timestamp: Long
    ): String {

        val formatter =
            SimpleDateFormat(
                "HH:mm:ss",
                Locale.US
            )

        formatter.timeZone =
            TimeZone.getTimeZone("UTC")

        return formatter.format(
            Date(timestamp)
        )
    }

    // =========================================================
    // Create fingerprint
    // =========================================================

    private fun createFingerprint(
        packageName: String,
        message: String,
        timestamp: Long
    ): String {

        /*
         * Round timestamp to one minute.
         */
        val roundedTimestamp =
            timestamp -
                    (
                            timestamp % 60_000L
                            )

        val raw =
            "$packageName|" +
                    "${message.trim().lowercase()}|" +
                    roundedTimestamp

        return MessageDigest
            .getInstance("SHA-256")
            .digest(
                raw.toByteArray()
            )
            .joinToString("") {
                "%02x".format(it)
            }
    }
}